/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sacip;

import org.junit.Test;

import sacip.Launcher;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Launcher classUnderTest = new Launcher();
        //assertNotNull("app should have a greeting", classUnderTest.main());
    }
}
